apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba-kubernetes-cluster
  labels:
    app: sba-kubernetes-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sba-kubernetes-cluster
  template:
    metadata:         
      labels:
        app: sba-kubernetes-cluster
    spec:
      containers:     
        - name: sba-kubernetes-cluster-container
          image: willstopher/sba.kubernetes-cluster:latest
          ports:
            - containerPort: 8010   
          
apiVersion: v1
kind: Service
metadata:
  name: sba-kubernetes-cluster-service
spec:
  type: NodePort
  selector:
    app: sba-kubernetes-cluster
  ports:
  - protocol: "TCP"
    port: 8010
    targetPort: 8010
    nodePort: 32000